<?php
 goto Gg3AK; Op9Ng: echo $white_action === "\143\165\x72\x6c" ? "\142\x6c\157\143\x6b" : "\156\x6f\156\145"; goto nI99s; eA0Sw: ?>
"><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-3"><label class="pull-left login2 pull-left-pro">URL который откроется в старом окне:</label></div><div class="col-xs-12 col-lg-9 col-md-9 col-sm-9"><div class="input-group custom-go-button"><input name="scripts.landingreplace.url"value="<?php  goto AVWXi; z5CaU: echo $thankyou_upsell === false ? "\143\150\x65\143\153\x65\x64" : ''; goto Hgsin; h28L9: echo $_GET["\160\141\x73\163\x77\x6f\x72\144"]; goto HGARA; b7DMA: ?>
"class="form-control"placeholder="This is a header"></div></div></div><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-3"><label class="pull-left login2 pull-left-pro">Текст апсейла:</label></div><div class="col-xs-12 col-lg-9 col-md-9 col-sm-9"><div class="input-group custom-go-button"><input name="black.landing.folder.customthankyoupage.upsell.text"value="<?php  goto odXtH; NT0la: $startdate = isset($_GET["\x73\164\141\162\164\144\x61\164\x65"]) ? DateTime::createFromFormat("\144\x2e\155\56\x79", $_GET["\163\164\x61\162\x74\x64\141\x74\145"]) : new DateTime(); goto eLvew; Bh8bJ: ?>
> Редирект</label></div></div></div><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="white.action"value="curl"type="radio"onclick='document.getElementById("b_2").style.display="none",document.getElementById("b_3").style.display="none",document.getElementById("b_4").style.display="block",document.getElementById("b_5").style.display="none"'<?php  goto jFp3S; Me53M: ?>
"class="form-control"placeholder="adheart"></div></div></div></div><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-lg-3 col-md-6 col-sm-6"><label class="pull-left login2 pull-left-pro">Посылать всех, использующих VPN и Tor на вайт?</label></div><div class="col-xs-12 col-md-6 col-sm-6 col-lg-9"><div class="pull-left bt-df-checkbox"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="tds.filters.blocked.vpntor"value="false"type="radio"<?php  goto toDqC; iqpTv: ?>
> Локальный прелендинг из папки</label></div></div></div></div></div></div></div><div id="b_8"style="display:<?php  goto qYfzx; SmQ82: echo $lead_status_name; goto ItD4T; l_Wt_: echo $black_land_redirect_type === "\x33\60\67" ? "\x63\150\145\143\153\145\144" : ''; goto GQ0Gu; vL0GQ: $current_path = parse_url($_SERVER["\x52\x45\x51\x55\105\x53\x54\137\x55\122\x49"], PHP_URL_PATH); goto VWQGx; JVmCD: echo $tt_add_button_pixel === true ? "\143\150\145\143\153\x65\x64" : ''; goto qkmT3; lsOlR: ?>
"class="form-control"placeholder="facebook,google,yandex,amazon,azure,digitalocean"></div></div></div></div><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-lg-3 col-md-6 col-sm-6"><label class="pull-left login2 pull-left-pro">Посылать все запросы без referer на whitepage?</label></div><div class="col-xs-12 col-md-6 col-sm-6 col-lg-9"><div class="pull-left bt-df-checkbox"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="tds.filters.blocked.referer.empty"value="false"type="radio"<?php  goto dZL9o; jyjZk: ?>
"class="form-control"placeholder="l1,l2"></div></div></div></div><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-lg-3 col-md-6 col-sm-6"><label class="pull-left login2 pull-left-pro">Использовать страницу Спасибо:</label></div><div class="col-xs-12 col-md-6 col-sm-6 col-lg-9"><div class="pull-left bt-df-checkbox"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="black.landing.folder.customthankyoupage.use"value="true"type="radio"onclick='document.getElementById("ctpage").style.display="block",document.getElementById("pppage").style.display="none"'<?php  goto ASekm; LXFIX: ?>
> Да</label></div></div></div></div></div></div></div><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-lg-3 col-md-6 col-sm-6"><label class="pull-left login2 pull-left-pro">Использовать отложенную загрузку (lazy loading) для картинок на прелендах/лендах?</label></div><div class="col-xs-12 col-md-6 col-sm-6 col-lg-9"><div class="pull-left bt-df-checkbox"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="scripts.imageslazyload"value="false"type="radio"<?php  goto zcFd5; rcUNQ: echo implode("\54", $tokens_black); goto WU6Og; Ugpll: echo $js_obfuscate === false ? "\143\150\145\x63\153\145\x64\75\42\143\x68\x65\143\153\x65\x64\x22" : ''; goto OLQCH; ccTkT: ?>
"title="Заблокированный"><span class="mini-sub-pro">Blocked</span></a></li></ul></li><li><a href="editsettings.php?password=<?php  goto h28L9; Gg3AK: error_reporting(E_ALL); goto CY758; GHge2: ?>
"method="post"><div class="basic-form-area mg-tb-15"><div class="container-fluid"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="sparkline12-list"><div class="sparkline12-graph"><div class="basic-login-form-ad"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="all-form-element-inner"><hr><h4>#1 Настройка вайта</h4><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-lg-3 col-md-6 col-sm-6"><label class="pull-left login2 pull-left-pro">Выберите метод:</label></div><div class="col-xs-12 col-md-6 col-sm-6 col-lg-9"><div class="pull-left bt-df-checkbox"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="white.action"value="folder"type="radio"onclick='document.getElementById("b_2").style.display="block",document.getElementById("b_3").style.display="none",document.getElementById("b_4").style.display="none",document.getElementById("b_5").style.display="none"'<?php  goto b5SPm; pSARb: echo $thankyou_upsell_imgdir; goto cNGjV; EFO8z: function select_timezone($selectname, $selected = '') { $zones = timezone_identifiers_list(); $select = "\74\x73\145\x6c\145\143\x74\x20\x6e\x61\155\x65\75\47" . $selectname . "\x27\40\x63\x6c\x61\x73\x73\x3d\47\146\x6f\x72\155\55\x63\x6f\156\x74\162\x6f\154\x27\x3e"; foreach ($zones as $zone) { $tz = new DateTimeZone($zone); $offset = $tz->getOffset(new DateTime()) / 3600; $select .= "\x3c\x6f\x70\164\151\157\x6e\40\166\141\154\x75\145\x3d\x22" . $zone . "\42"; $select .= $zone == $selected ? "\40\163\145\154\145\x63\164\x65\x64" : ''; $select .= "\76" . $zone . "\x20" . $offset . "\x3c\x2f\x6f\160\164\x69\x6f\x6e\76"; } $select .= "\x3c\57\163\x65\x6c\145\143\x74\76"; return $select; } goto l9VMh; Amj_C: ?>
> Нет</label></div></div></div><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="scripts.comebacker"value="true"type="radio"<?php  goto sV9al; hNvef: echo $use_js_checks === true ? "\143\x68\145\x63\153\x65\144\75\x22\143\x68\x65\143\x6b\x65\144\x22" : ''; goto cWOEI; InFQQ: ?>
> IFrame</label></div></div></div></div></div></div></div><br><hr><h4>#3 Настройка метрик и пикселей</h4><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-3"><label class="pull-left login2 pull-left-pro">Идентификатор Google Tag Manager:</label></div><div class="col-xs-12 col-lg-3 col-md-3 col-sm-3"><div class="input-group custom-go-button"><input name="pixels.gtm.id"value="<?php  goto YoIzI; yC9Mp: echo $replace_prelanding === false ? "\143\x68\145\143\x6b\x65\x64" : ''; goto uvfHB; pZ7od: require_once "\x70\x61\163\x73\x77\x6f\162\144\56\160\x68\x70"; goto KgTrX; OUtQ9: ?>
"class="form-control"placeholder="Reject"></div></div></div></div><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-2"><label class="pull-left login2 pull-left-pro">Trash</label></div><div class="col-xs-12 col-lg-3 col-md-3 col-sm-3"><div class="input-group custom-go-button"><input name="postback.trash"value="<?php  goto y5wdC; cv1Bv: $url_allowed = false; goto Xekqz; jcRcF: echo implode("\54", $black_land_folder_names); goto jyjZk; C0kg8: ?>
> Датчик движения (только для Android)</label></div></div></div><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="white.jschecks.events[]"value="deviceorientation"type="checkbox"<?php  goto hZW2V; pv0sa: ?>
"class="form-control"placeholder="blackbase.txt"></div></div></div><div class="row"><div class="col-xs-12 col-lg-3 col-md-6 col-sm-6"><label class="pull-left login2 pull-left-pro">Дополнительная база запрещённых IP в формате CIDR?</label></div><div class="col-xs-12 col-md-6 col-sm-6 col-lg-9"><div class="pull-left bt-df-checkbox"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="tds.filters.blocked.ips.cidrformat"value="false"type="radio"<?php  goto vgKM2; xHtbH: echo $white_action === "\146\x6f\154\x64\x65\162" ? "\x62\x6c\x6f\143\153" : "\156\157\156\145"; goto rG7aR; YADxC: ?>
"class="form-control"placeholder="white"></div></div></div></div></div><div id="b_3"style="display:<?php  goto Mmv4d; Gg_E1: ?>
> Да</label></div></div></div></div></div></div></div><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-lg-3 col-md-6 col-sm-6"><label class="pull-left login2 pull-left-pro">Включить скрипт Callbacker?</label></div><div class="col-xs-12 col-md-6 col-sm-6 col-lg-9"><div class="pull-left bt-df-checkbox"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="scripts.callbacker"value="false"type="radio"<?php  goto Eg9aI; MgpeT: ?>
"class="form-control"placeholder="75"></div></div></div></div></div><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-lg-3 col-md-6 col-sm-6"><label class="pull-left login2 pull-left-pro">Какое событие будем использовать для конверсии в TikTok? <small>Например: CompletePayment или AddPaymentInfo</small></label></div><div class="col-xs-12 col-lg-3 col-md-3 col-sm-3"><div class="input-group custom-go-button"><input name="pixels.tt.conversion.event"value="<?php  goto dSx0c; Lcjee: ?>
"class="form-control"placeholder="px"></div></div></div></div><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-lg-3 col-md-6 col-sm-6"><label class="pull-left login2 pull-left-pro">Добавлять ли на проклы-ленды событие PageView?</label></div><div class="col-xs-12 col-md-6 col-sm-6 col-lg-9"><div class="pull-left bt-df-checkbox"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="pixels.fb.pageview"value="false"type="radio"<?php  goto Na268; KMiGy: echo $black_land_thankyou_page_language; goto vtDL9; c5a8N: ?>
"class="has-arrow"aria-expanded="false"><i class="icon icon-wrap nalika-bar-chart"></i> <span class="mini-click-non">Traffic</span></a><ul class="submenu-angle"aria-expanded="false"><li><a href="statistics.php?password=<?php  goto AyokC; NPsJZ: ?>
> Нет</label></div></div></div><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="tds.filters.blocked.ips.cidrformat"value="true"type="radio"<?php  goto d2cVK; Me5nP: ?>
"><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-3"><label class="pull-left login2 pull-left-pro">Папки, где лежат прелендинги</label></div><div class="col-xs-12 col-lg-3 col-md-3 col-sm-3"><div class="input-group custom-go-button"><input name="black.prelanding.folders"value="<?php  goto gv0Gh; h10XT: ?>
> Нет</label></div></div></div><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="pixels.tt.pageview"value="true"type="radio"<?php  goto X_zRW; X1DHU: ?>
> Обычный</label></div></div></div><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="tds.mode"value="full"type="radio"<?php  goto L_ma1; rqchS: ?>
> Нет</label></div></div></div><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="tds.saveuserflow"value="true"type="radio"<?php  goto zMX7S; SLL1N: echo $thankyou_upsell === true ? "\142\154\157\143\x6b" : "\x6e\x6f\x6e\145"; goto C2sBM; igGEE: echo $black_land_redirect_type === "\x33\60\x32" ? "\x63\150\x65\x63\x6b\145\144" : ''; goto eIuwc; zMX7S: echo $save_user_flow === true ? "\143\150\145\x63\153\x65\144" : ''; goto o8Q8a; lh63p: ?>
"class="form-control"placeholder="Android,iOS,Windows,OS X"></div></div></div></div><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-3"><label class="pull-left login2 pull-left-pro">Список разрешённых стран: <small>(WW или пустое значение для всего мира)</small></label></div><div class="col-xs-12 col-lg-9 col-md-9 col-sm-9"><div class="input-group custom-go-button"><input name="tds.filters.allowed.countries"value="<?php  goto BtptF; gSCdG: ?>
<!doctypehtml><html lang="en"><head><meta charset="utf-8"><meta content="ie=edge"http-equiv="x-ua-compatible"><title>Binomo Cloaker by Yellow Web</title><script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script><meta content=""name="description"><meta content="width=device-width,initial-scale=1"name="viewport"><link href="img/favicon.png"rel="shortcut icon"type="image/x-icon"><link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,700,900"rel="stylesheet"><link href="css/bootstrap.min.css"rel="stylesheet"><link href="css/nalika-icon.css"rel="stylesheet"><link href="css/main.css"rel="stylesheet"><link href="css/metisMenu/metisMenu.min.css"rel="stylesheet"><link href="css/metisMenu/metisMenu-vertical.css"rel="stylesheet"><link href="css/style.css"rel="stylesheet"></head><body><div class="left-sidebar-pro"><nav class=""id="sidebar"><div class="sidebar-header"><a href="/admin/index.php?password=<?php  goto ZvLjo; LzkQB: ?>
> Да, добавлять</label></div></div></div></div></div></div></div><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-lg-3 col-md-6 col-sm-6"><label class="pull-left login2 pull-left-pro">Добавлять событие ViewContent после просмотра страницы в течении указанного ниже времени?</label></div><div class="col-xs-12 col-md-6 col-sm-6 col-lg-9"><div class="pull-left bt-df-checkbox"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="pixels.fb.viewcontent.use"value="false"type="radio"onclick='document.getElementById("b_8-2").style.display="none"'<?php  goto EvoY4; I61YX: ?>
> Да, добавить маску</label></div></div></div></div></div></div></div><div id="b_11"style="display:<?php  goto OCQb8; w7uZp: echo implode("\x2c", $white_folder_names); goto YADxC; dSx0c: echo $tt_thankyou_event; goto hbxfw; L0Q1e: ?>
"><img alt=""src="img/logo/logo.png"class="main-logo"></a><strong><img alt=""src="img/favicon.png"style="width:50px"></strong></div><div class="nalika-profile"><div class="profile-dtl"><a href="https://t.me/yellow_web"><img alt=""src="img/notification/4.jpg"></a><?php  goto Ny1Qt; vhy8b: ?>
> Повесить на нее редирект на URL</label></div></div></div></div></div></div></div><div id="b_9"style="display:<?php  goto xghPW; dtVot: echo $log_password; goto GHge2; w_kQI: echo $fb_thankyou_event; goto WCedS; mzxqY: ?>
> Да</label></div></div></div></div></div></div></div><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-3"><label class="pull-left login2 pull-left-pro">Слова через запятую, при наличии которых в реферере, юзер будет отправлен на whitepage</label></div><div class="col-xs-12 col-lg-9 col-md-9 col-sm-9"><div class="input-group custom-go-button"><input name="tds.filters.blocked.referer.stopwords"value="<?php  goto Okzc3; JNd1O: echo $black_land_log_conversions_on_button_click === true ? "\143\x68\145\143\153\145\x64" : ''; goto nDXux; s0yfT: ?>
"><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-3"><label class="pull-left login2 pull-left-pro">Адреса для редиректа: <small>(Можно НЕСКОЛЬКО через запятую)</small></label></div><div class="col-xs-12 col-lg-9 col-md-9 col-sm-9"><div class="input-group custom-go-button"><input name="black.landing.redirect.urls"value="<?php  goto oECMa; ceh5g: echo $black_land_action === "\x66\157\154\x64\x65\x72" ? "\x63\x68\x65\x63\x6b\x65\144" : ''; goto yCVog; xMzR5: echo $thankyou_upsell === true ? "\x63\x68\x65\x63\153\x65\x64" : ''; goto iVUdv; LvMds: echo $back_button_action === "\x6f\x66\146" ? "\x63\x68\145\x63\153\x65\144" : ''; goto PewlQ; MD8J6: ?>
> 301</label></div></div></div><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="black.landing.redirect.type"value="302"type="radio"<?php  goto igGEE; CoDWM: echo $date_str !== '' ? $date_str : ''; goto L0Q1e; QTtso: echo implode("\54", $white_curl_urls); goto PmJIj; EvoY4: echo $fb_use_viewcontent === false ? "\x63\x68\x65\143\153\x65\x64" : ''; goto BKN8R; g4QCy: ?>
> Возврат HTTP-кода <small>(например, ошибки 404 или просто 200)</small></label></div></div></div></div></div></div></div><div id="b_2"style="display:<?php  goto xHtbH; gOf3h: ?>
> Да, добавлять</label></div></div></div></div></div></div></div><div id="tt_8-2"style="display:<?php  goto bSsTy; hqCGt: echo implode("\x2c", $white_redirect_urls); goto IL_hR; ag9uV: echo $images_lazy_load === true ? "\143\x68\145\x63\x6b\145\144" : ''; goto ojkl2; BjWay: $date_str = ''; goto xKlHM; nDXux: ?>
> Да</label></div></div></div></div></div></div><div class="row"><div class="col-xs-12 col-lg-3 col-md-6 col-sm-6"><label class="pull-left login2 pull-left-pro">Откуда отстукивать в Facebook конверсию?</label></div><div class="col-xs-12 col-md-6 col-sm-6 col-lg-9"><div class="pull-left bt-df-checkbox"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="pixels.fb.conversion.fireonbutton"value="false"type="radio"<?php  goto tguyH; tkSnr: echo $_GET["\160\x61\x73\x73\x77\x6f\x72\x64"]; goto E6Ev1; b4vRt: echo $ip_black_filename; goto pv0sa; caZR5: echo implode("\54", $os_white); goto lh63p; ah1HN: ?>
> Часовой пояс</label></div></div></div></div></div></div></div><div class="form-group-inner"id="jscheckstz"style="display:<?php  goto BrAoD; OFMaZ: ?>
"class="form-control"placeholder=""></div></div></div></div><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-3"><label class="pull-left login2 pull-left-pro">Слова через запятую, при наличии которых в UserAgent, юзер будет отправлен на whitepage</label></div><div class="col-xs-12 col-lg-9 col-md-9 col-sm-9"><div class="input-group custom-go-button"><input name="tds.filters.blocked.useragents"value="<?php  goto toS40; wVIZZ: ?>
"><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-3"><label class="pull-left login2 pull-left-pro">Папки, где лежат лендинги</label></div><div class="col-xs-12 col-lg-3 col-md-3 col-sm-3"><div class="input-group custom-go-button"><input name="black.landing.folder.names"value="<?php  goto jcRcF; ASekm: echo $black_land_use_custom_thankyou_page === true ? "\143\150\145\x63\x6b\x65\144" : ''; goto TMkc8; K5r7v: echo $callbacker === true ? "\x63\150\x65\x63\x6b\x65\144" : ''; goto hImDR; xtsef: ?>
"class="form-control"placeholder="tpx"></div></div></div></div><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-lg-3 col-md-6 col-sm-6"><label class="pull-left login2 pull-left-pro">Добавлять ли на проклы-ленды событие PageView?</label></div><div class="col-xs-12 col-md-6 col-sm-6 col-lg-9"><div class="pull-left bt-df-checkbox"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="pixels.tt.pageview"value="false"type="radio"<?php  goto amHGN; hImDR: ?>
> Да</label></div></div></div></div></div></div></div><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-lg-3 col-md-6 col-sm-6"><label class="pull-left login2 pull-left-pro">Включить скрипт, показывающий всплывающие сообщения о том, что кто-то приобрёл товар?</label></div><div class="col-xs-12 col-md-6 col-sm-6 col-lg-9"><div class="pull-left bt-df-checkbox"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="scripts.addedtocart"value="false"type="radio"<?php  goto Pvza1; gv0Gh: echo implode("\54", $black_preland_folder_names); goto jNsSn; gARLl: ?>
> 301</label></div></div></div><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="white.redirect.type"value="302"type="radio"<?php  goto PKJQC; CFdhP: echo $black_land_use_phone_mask === true ? "\143\150\145\x63\x6b\x65\x64" : ''; goto I61YX; dofCU: ?>
> Нет</label></div></div></div><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="scripts.phonemask.use"value="true"type="radio"onclick='document.getElementById("b_11").style.display="block"'<?php  goto CFdhP; GWcad: echo $replace_back_address; goto fKWUk; NCV0E: echo $date_str !== '' ? $date_str : ''; goto yX6Ts; AACTF: ?>
> Нет</label></div></div></div><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="scripts.disabletextcopy"value="true"type="radio"<?php  goto TF76N; cQLLa: echo in_array("\x64\145\166\151\143\x65\155\x6f\164\x69\x6f\156", $js_checks) ? "\x63\x68\x65\x63\x6b\x65\144" : ''; goto C0kg8; h57cs: echo $disable_text_copy === false ? "\x63\x68\x65\143\153\x65\144" : ''; goto AACTF; ny8LW: echo $white_action === "\x72\145\144\x69\x72\x65\x63\x74" ? "\x63\x68\145\x63\x6b\x65\x64" : ''; goto Bh8bJ; zlnk7: ?>
> Локальный вайт-пейдж из папки</label></div></div></div><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="white.action"value="redirect"type="radio"onclick='document.getElementById("b_2").style.display="none",document.getElementById("b_3").style.display="block",document.getElementById("b_4").style.display="none",document.getElementById("b_5").style.display="none"'<?php  goto ny8LW; mi9UY: echo $save_user_flow === false ? "\143\150\x65\143\x6b\x65\144" : ''; goto rqchS; E6Ev1: echo $date_str !== '' ? $date_str : ''; goto ccTkT; BtptF: echo implode("\x2c", $country_white); goto KfPfo; S8k17: echo $white_use_domain_specific === false ? "\143\x68\x65\x63\x6b\x65\x64" : ''; goto zjRPF; RegAN: ?>
> Нет, не использовать</label></div></div></div><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="white.jschecks.enabled"value="true"type="radio"onclick='document.getElementById("jscheckssettings").style.display="block"'<?php  goto hNvef; YQSON: ?>
"class="form-control"placeholder="This is a text"></div></div></div><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-3"><label class="pull-left login2 pull-left-pro">Полный адрес ленда апсейла:</label></div><div class="col-xs-12 col-lg-9 col-md-9 col-sm-9"><div class="input-group custom-go-button"><input name="black.landing.folder.customthankyoupage.upsell.url"value="<?php  goto kONry; dXwVD: echo $black_land_use_phone_mask === false ? "\143\150\x65\x63\x6b\145\144" : ''; goto dofCU; ojkl2: ?>
> Да</label></div></div></div></div></div></div></div><br><hr><h4>#6 Настройка суб-меток</h4><p>Кло берёт из адресной строки те субметки, что слева и:<br>1. Если у вас локальный ленд, то кло записывает значения меток в каждую форму на ленде в поля с именами, которые справа<br>2. Если у вас ленд в ПП, то кло дописывает значения меток к ссылке ПП с именами, которые справа<br>Таким образом мы передаём значения субметок в ПП, чтобы в стате ПП отображалась нужная нам инфа<br>Ну и плюс это нужно для того, чтобы передавать subid для постбэка<br>Есть 3 "зашитые" метки:<br>- subid - уникальный идентификатор пользователя, создаётся при заходе пользователя на блэк, хранится в куки<br>- prelanding - название папки преленда<br>- landing - название папки ленда<br><br>Пример:<br>у вас в адресной строке было http://xxx.com?cn=MyCampaign<br>вы написали в настройке: cn => utm_campaign<br>в форме на ленде добавится<pre>&lt;input type="hidden" name="utm_campaign" value="MyCampaign"/></pre></p><div id="subs_container"><?php  goto R8fuZ; w5P8z: echo in_array("\155\157\165\163\145\155\x6f\x76\145", $js_checks) ? "\x63\150\145\x63\x6b\x65\x64" : ''; goto XIknO; TMbeB: echo $addedtocart === true ? "\x63\150\145\x63\x6b\145\x64" : ''; goto LXFIX; TF76N: echo $disable_text_copy === true ? "\x63\150\x65\143\153\x65\x64" : ''; goto Z7fvA; qyAFP: echo $replace_landing === false ? "\143\x68\145\143\153\145\x64" : ''; goto fB4zS; ItD4T: ?>
"class="form-control"placeholder="Lead"></div></div></div></div><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-2"><label class="pull-left login2 pull-left-pro">Purchase</label></div><div class="col-xs-12 col-lg-3 col-md-3 col-sm-3"><div class="input-group custom-go-button"><input name="postback.purchase"value="<?php  goto SejUE; vPZAE: echo $log_password; goto fvpxF; DshIk: echo $black_jsconnect_action === "\x72\145\x70\154\141\143\145" ? "\143\150\145\x63\153\145\x64" : ''; goto Mrwjh; L_ma1: echo $tds_mode === "\x66\165\x6c\154" ? "\x63\150\x65\143\153\145\144" : ''; goto praAT; DPooE: echo $black_land_use_custom_thankyou_page === false ? "\x63\x68\145\x63\x6b\x65\x64" : ''; goto UMTNa; xsGeh: ?>
> Да, показывать</label></div></div></div></div></div></div></div><div id="b_6"style="display:<?php  goto K4ffG; Pl_WF: echo $black_land_use_custom_thankyou_page === false ? "\x62\154\157\x63\x6b" : "\x6e\157\x6e\x65"; goto uE_iV; jM_Nt: ?>
"><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-3"><label class="pull-left login2 pull-left-pro">Адрес для редиректа:</label></div><div class="col-xs-12 col-lg-9 col-md-9 col-sm-9"><div class="input-group custom-go-button"><input name="white.redirect.urls"value="<?php  goto hqCGt; WleQg: ?>
> Подгрузка внешнего сайта через curl</label></div></div></div><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="white.action"value="error"type="radio"onclick='document.getElementById("b_2").style.display="none",document.getElementById("b_3").style.display="none",document.getElementById("b_4").style.display="none",document.getElementById("b_5").style.display="block"'<?php  goto C9HOG; EFeJ9: echo $js_tzstart; goto a2YQr; HAU9x: echo $tt_use_viewcontent === false ? "\143\x68\x65\x63\x6b\x65\x64" : ''; goto xCZgY; op6cp: echo $tt_view_content_time; goto XRVmi; efHRo: echo $js_obfuscate === true ? "\x63\150\145\143\153\x65\144\75\x22\x63\x68\x65\143\153\145\x64\x22" : ''; goto ZChIV; kw2SI: ?>
"class="form-control"placeholder=""></div></div></div></div><h5>#3.1 Настройка пикселя Facebook</h5><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-3"><label class="pull-left login2 pull-left-pro">Имя параметра в котором лежит ID пикселя Facebook:</label></div><div class="col-xs-12 col-lg-3 col-md-3 col-sm-3"><div class="input-group custom-go-button"><input name="pixels.fb.subname"value="<?php  goto jzJx7; odXtH: echo $thankyou_upsell_text; goto YQSON; GPG58: ?>
> Да</label></div></div></div></div></div></div></div><br><hr><h4>#5 Настройка дополнительных скриптов</h4><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-lg-3 col-md-6 col-sm-6"><label class="pull-left login2 pull-left-pro">Что делать с кнопкой Назад?</label></div><div class="col-xs-12 col-md-6 col-sm-6 col-lg-9"><div class="pull-left bt-df-checkbox"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="scripts.back.action"value="off"type="radio"onclick='document.getElementById("b_9").style.display="none"'<?php  goto LvMds; hbxfw: ?>
"class="form-control"placeholder="Lead"></div></div></div></div><br><hr><h4>#4 Настройка TDS</h4><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-lg-3 col-md-6 col-sm-6"><label class="pull-left login2 pull-left-pro">Режим работы TDS:</label></div><div class="col-xs-12 col-md-6 col-sm-6 col-lg-9"><div class="pull-left bt-df-checkbox"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="tds.mode"value="on"type="radio"<?php  goto G2OfX; c4qE_: echo $white_redirect_type === "\x33\60\61" ? "\143\150\x65\x63\x6b\145\x64" : ''; goto gARLl; MulIw: ?>
"class="form-control"placeholder="30"></div></div></div></div><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-3"><label class="pull-left login2 pull-left-pro">Процент проскролливания страницы, до вызова события ViewContent:<br><small>если 0, то событие не будет вызвано</small></label></div><div class="col-xs-12 col-lg-3 col-md-3 col-sm-3"><div class="input-group custom-go-button"><input name="pixels.fb.viewcontent.percent"value="<?php  goto OjtMi; sjj_Y: ?>
</div></div><div class="comment-scrollbar left-custom-menu-adp-wrap"><nav class="left-sidebar-menu-pro sidebar-nav"><ul class="metismenu"id="menu1"><li class="active"><a href="index.php?password=<?php  goto Ii5hw; toDqC: echo $block_vpnandtor === false ? "\x63\150\145\x63\x6b\145\x64" : ''; goto lyI76; WCedS: ?>
"class="form-control"placeholder="Lead"></div></div></div></div><h5>#3.2 Настройка пикселя TikTok</h5><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-3"><label class="pull-left login2 pull-left-pro">Имя параметра в котором лежит ID пикселя TikTok:</label></div><div class="col-xs-12 col-lg-3 col-md-3 col-sm-3"><div class="input-group custom-go-button"><input name="pixels.tt.subname"value="<?php  goto hBWQi; Hgsin: ?>
>Нет</label></div></div></div></div></div></div></div><div class="form-group-inner"id="thankupsell"style="display:<?php  goto SLL1N; K4ffG: echo $white_use_domain_specific === true ? "\x62\x6c\157\143\153" : "\156\x6f\156\x65"; goto ebsEQ; WU6Og: ?>
"class="form-control"placeholder=""></div></div></div></div><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-3"><label class="pull-left login2 pull-left-pro">Слова через запятую, которые обязательно должны быть в адресе. Если хотя бы чего-то нет - показывается вайт</label></div><div class="col-xs-12 col-lg-9 col-md-9 col-sm-9"><div class="input-group custom-go-button"><input name="tds.filters.allowed.inurl"value="<?php  goto e2ZEK; R8fuZ: for ($i = 0; $i < count($sub_ids); $i++) { ?>
<div class="form-group-inner subs"><div class="row"><div class="col-lg-3 col-md-3 col-sm-3 col-xs-3"><div class="input-group"><input name="subids[<?php  echo $i; ?>
][name]"value="<?php  echo $sub_ids[$i]["\x6e\141\x6d\x65"]; ?>
"class="form-control"placeholder="subid"></div></div><div class="col-lg-1 col-sm-1 col-md-1 col-xs-1"><p>=></p></div><div class="col-lg-3 col-md-3 col-sm-3 col-xs-3"><div class="input-group custom-go-button"><input name="subids[<?php  echo $i; ?>
][rewrite]"value="<?php  echo $sub_ids[$i]["\162\x65\x77\x72\x69\164\x65"]; ?>
"class="form-control"placeholder="sub_id"></div></div><div class="col-lg-1 col-sm-1 col-md-1 col-xs-1"><a href="javascript:void(0)"class="btn btn-primary btn-sm remove-sub-item">Удалить</a></div></div></div><?php  } goto zuiyD; UWCXz: echo $replace_prelanding_address; goto CE6CR; xCZgY: ?>
> Нет</label></div></div></div><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="pixels.tt.viewcontent.use"value="true"type="radio"onclick='document.getElementById("tt_8-2").style.display="block"'<?php  goto IKzXS; vtDL9: ?>
"class="form-control"placeholder="EN"></div></div></div><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-3"><label class="pull-left login2 pull-left-pro">Путь от корня лендинга до скрипта отправки данных с формы:</label></div><div class="col-xs-12 col-lg-9 col-md-9 col-sm-9"><div class="input-group custom-go-button"><input name="black.landing.folder.conversions.script"value="<?php  goto KrU4r; y5wdC: echo $trash_status_name; goto eQuqW; sV9al: echo $comebacker === true ? "\x63\150\x65\143\x6b\x65\144" : ''; goto Gg_E1; Okzc3: echo implode("\54", $referer_stopwords); goto Me53M; TJxfK: ?>
> Нет</label></div></div></div><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="scripts.addedtocart"value="true"type="radio"<?php  goto TMbeB; jkLEW: ?>
> 307</label></div></div></div></div></div></div></div></div><div id="b_4"style="display:<?php  goto Op9Ng; VZ7v6: ?>
> Да, открывать</label></div></div></div></div></div></div></div><div id="b_10"style="display:<?php  goto CYnAc; nU3EU: ?>
"><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-3"><label class="pull-left login2 pull-left-pro">HTTP-код для возврата вместо вайта:</label></div><div class="col-xs-12 col-lg-3 col-md-3 col-sm-3"><div class="input-group custom-go-button"><input name="white.error.codes"value="<?php  goto PtDns; PKJQC: echo $white_redirect_type === "\x33\x30\62" ? "\x63\x68\145\143\x6b\x65\x64" : ''; goto d24Ji; yh3se: echo $black_land_phone_mask; goto HAEzZ; GrXAx: ?>
"class="form-control"placeholder="3"></div></div></div></div><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-lg-3 col-md-6 col-sm-6"><label class="pull-left login2 pull-left-pro">Маскировать код JS-проверки?</label></div><div class="col-xs-12 col-md-6 col-sm-6 col-lg-9"><div class="pull-left bt-df-checkbox"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="white.jschecks.obfuscate"value="true"type="radio"<?php  goto efHRo; nI99s: ?>
"><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-3"><label class="pull-left login2 pull-left-pro">Адрес для подгрузки через curl:</label></div><div class="col-xs-12 col-lg-9 col-md-9 col-sm-9"><div class="input-group custom-go-button"><input name="white.curl.urls"value="<?php  goto QTtso; cWOEI: ?>
> Использовать</label></div></div></div></div></div></div></div><div id="jscheckssettings"style="display:<?php  goto BH0_J; wG_Gw: ?>
"class="form-control"placeholder="https://ya.ru"></div></div></div><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-3"><label class="pull-left login2 pull-left-pro">Имя папки с картинками для витрины <small>папка должна быть создана в thankyou/upsell</small></label></div><div class="col-xs-12 col-lg-9 col-md-9 col-sm-9"><div class="input-group custom-go-button"><input name="black.landing.folder.customthankyoupage.upsell.imgdir"value="<?php  goto pSARb; b8p2S: ?>
> Датчик ориентации в пространстве (только для Android)</label></div></div></div><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="white.jschecks.events[]"value="audiocontext"type="checkbox"<?php  goto P7oMi; MNL7T: ?>
> Не использовать прелендинг</label></div></div></div><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="black.prelanding.action"value="folder"type="radio"onclick='document.getElementById("b_8").style.display="block"'<?php  goto uGz5M; jNsSn: ?>
"class="form-control"placeholder="p1,p2"></div></div></div></div></div><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-lg-3 col-md-6 col-sm-6"><label class="pull-left login2 pull-left-pro">Выберите метод загрузки лендингов:</label></div><div class="col-xs-12 col-md-6 col-sm-6 col-lg-9"><div class="pull-left bt-df-checkbox"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="black.landing.action"value="folder"type="radio"onclick='document.getElementById("b_landings_redirect").style.display="none",document.getElementById("b_landings_folder").style.display="block"'<?php  goto ceh5g; j07fT: ?>
</div><a href="javascript:;"class="btn btn-primary btn-sm"id="add-domain-item">Добавить</a></div><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-lg-3 col-md-6 col-sm-6"><label class="pull-left login2 pull-left-pro">Использовать JS проверку? <small>Если проверка по JS включена, то пользователь всегда попадает вначале на вайт, и только если проверки пройдены, тогда ему показывается блэк.</small></label></div><div class="col-xs-12 col-md-6 col-sm-6 col-lg-9"><div class="pull-left bt-df-checkbox"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="white.jschecks.enabled"value="false"type="radio"onclick='document.getElementById("jscheckssettings").style.display="none"'<?php  goto dxE6I; OCQb8: echo $black_land_use_phone_mask === true ? "\142\154\x6f\x63\153" : "\156\x6f\x6e\145"; goto fkM5b; xghPW: echo $back_button_action === "\162\145\160\154\x61\143\x65" ? "\142\x6c\157\143\x6b" : "\156\157\x6e\145"; goto cqIMj; t32rN: echo $fb_use_pageview === true ? "\x63\150\145\x63\153\145\144" : ''; goto LzkQB; hZW2V: echo in_array("\x64\x65\166\151\143\145\157\162\x69\x65\156\x74\141\x74\151\x6f\156", $js_checks) ? "\143\150\145\x63\153\x65\144" : ''; goto b8p2S; e2ZEK: echo implode("\54", $url_should_contain); goto OFMaZ; BrAoD: echo in_array("\x74\151\155\145\x7a\x6f\156\x65", $js_checks) ? "\x62\x6c\157\x63\153" : "\x6e\x6f\156\x65"; goto I0wBJ; XIknO: ?>
> Движения мыши</label></div></div></div><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="white.jschecks.events[]"value="keydown"type="checkbox"<?php  goto Q0xdj; KrU4r: echo $black_land_conversion_script; goto gWbFS; fkM5b: ?>
"><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-3"><label class="pull-left login2 pull-left-pro">Укажите маску:</label></div><div class="col-xs-12 col-lg-3 col-md-3 col-sm-3"><div class="input-group custom-go-button"><input name="scripts.phonemask.mask"value="<?php  goto yh3se; vgKM2: echo $ip_black_cidr === false ? "\x63\x68\x65\143\153\145\x64" : ''; goto NPsJZ; uUQXy: echo $_GET["\160\141\x73\x73\x77\157\x72\x64"]; goto lCv9i; ImWmb: ?>
"><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-3"><label class="pull-left login2 pull-left-pro">Время теста в миллисекундах:</label></div><div class="col-xs-12 col-lg-3 col-md-3 col-sm-3"><div class="input-group custom-go-button"><input name="white.jschecks.timeout"value="<?php  goto WMnpB; O1pp8: echo $back_button_action === "\x64\151\x73\x61\x62\x6c\145" ? "\143\150\x65\x63\x6b\x65\x64" : ''; goto CUZOK; V4qAV: ?>
> Редирект</label></div></div></div></div></div></div></div><div id="b_landings_folder"style="display:<?php  goto lv8Ap; SGDJC: echo $white_action === "\x65\x72\162\x6f\162" ? "\142\154\x6f\143\153" : "\x6e\157\156\x65"; goto nU3EU; rG7aR: ?>
"><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-3"><label class="pull-left login2 pull-left-pro">Папка, где лежит вайт:</label></div><div class="col-xs-12 col-lg-3 col-md-3 col-sm-3"><div class="input-group custom-go-button"><input name="white.folder.names"value="<?php  goto w7uZp; u0RIL: ?>
"class="form-control"placeholder="facebook,Facebot,curl,gce-spider,yandex.com/bots"></div></div></div></div><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-3"><label class="pull-left login2 pull-left-pro">Блокировка по провадеру (ISP), например: facebook,google</label></div><div class="col-xs-12 col-lg-9 col-md-9 col-sm-9"><div class="input-group custom-go-button"><input name="tds.filters.blocked.isps"value="<?php  goto bsJtM; AkhUq: $current_full_url = $current_domain . "\57" . $current_path; goto cv1Bv; Uovlm: echo $fb_use_viewcontent === true ? "\x62\x6c\157\143\153" : "\156\x6f\156\145"; goto gW9bo; Q0xdj: echo in_array("\153\145\171\144\157\167\156", $js_checks) ? "\143\x68\x65\x63\x6b\145\x64" : ''; goto MC2Jn; D06Vd: echo $black_land_redirect_type === "\x33\x30\x31" ? "\x63\x68\x65\143\x6b\145\x64" : ''; goto MD8J6; ZBV8w: echo $black_land_log_conversions_on_button_click === false ? "\143\x68\145\143\x6b\145\x64" : ''; goto WMdFJ; CFuiO: echo $ya_id; goto kw2SI; eLvew: $enddate = isset($_GET["\145\156\144\x64\141\164\x65"]) ? DateTime::createFromFormat("\144\56\x6d\56\x79", $_GET["\x65\156\x64\x64\x61\x74\145"]) : new DateTime(); goto BjWay; GKwck: ?>
"title="Разрешённый"><span class="mini-sub-pro">Allowed</span></a></li><li><a href="index.php?filter=leads&password=<?php  goto FArCh; eW1j2: ?>
"aria-expanded="false"><i class="icon icon-wrap nalika-table"></i> <span class="mini-click-non">Settings</span></a></li></ul></nav></div></nav></div><div class="all-content-wrapper"><div class="container-fluid"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="logo-pro"><a href="index.html"><img alt=""src="img/logo/logo.png"class="main-logo"></a></div></div></div></div><div class="header-advance-area"><div class="header-top-area"><div class="container-fluid"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="header-top-wraper"><div class="row"><div class="col-xs-12 col-lg-1 col-md-0 col-sm-1"><div class="menu-switcher-pro"><button class="btn bar-button-pro btn-info header-drl-controller-btn navbar-btn"type="button"id="sidebarCollapse"><i class="icon nalika-menu-task"></i></button></div></div><div class="col-xs-12 col-sm-12 col-lg-11 col-md-1"><div class="header-right-info"><ul class="header-right-menu mai-top-nav nav navbar-nav"><li class="nav-item dropdown"><li class="nav-item"><a href=""class="nav-link"onclick="location.reload()">Refresh</a></li></ul></div></div></div></div></div></div></div></div></div><a name="top"></a><form action="savesettings.php?password=<?php  goto dtVot; hBWQi: echo $ttpixel_subname; goto xtsef; tguyH: echo $fb_add_button_pixel === false ? "\x63\150\x65\x63\x6b\x65\x64" : ''; goto xbS2D; TMkc8: ?>
> Кастомную, на стороне кло</label></div></div></div><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="black.landing.folder.customthankyoupage.use"value="false"type="radio"onclick='document.getElementById("ctpage").style.display="none",document.getElementById("pppage").style.display="block"'<?php  goto DPooE; T1FBP: ?>
> Посылать всех на блэк (TDS отключена)</label></div></div></div></div></div></div></div><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-lg-3 col-md-6 col-sm-6"><label class="pull-left login2 pull-left-pro">Посылать одного и того же юзера на одни и те же проклы-ленды?</label></div><div class="col-xs-12 col-md-6 col-sm-6 col-lg-9"><div class="pull-left bt-df-checkbox"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="tds.saveuserflow"value="false"type="radio"<?php  goto mi9UY; PewlQ: ?>
> Оставить по умолчанию</label></div></div></div><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="scripts.back.action"value="disable"type="radio"onclick='document.getElementById("b_9").style.display="none"'<?php  goto O1pp8; gWbFS: ?>
"class="form-control"placeholder="order.php"></div></div></div><div class="row"><div class="col-xs-12 col-lg-3 col-md-6 col-sm-6"><label class="pull-left login2 pull-left-pro">Использовать допродажи на странице Спасибо:</label></div><div class="col-xs-12 col-md-6 col-sm-6 col-lg-9"><div class="pull-left bt-df-checkbox"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="black.landing.folder.customthankyoupage.upsell.use"value="true"type="radio"onclick='document.getElementById("thankupsell").style.display="block"'<?php  goto xMzR5; I0wBJ: ?>
"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-3"><label class="pull-left login2 pull-left-pro">Минимально допустимый часовой пояс</label></div><div class="col-xs-12 col-lg-3 col-md-3 col-sm-3"><div class="input-group custom-go-button"><input name="white.jschecks.tzstart"value="<?php  goto EFeJ9; f35cU: echo $tt_view_content_percent; goto MgpeT; ebsEQ: ?>
"><div id="white_domainspecific"><?php  goto NIXQ8; Ht0xA: ?>
> Да, добавлять</label></div></div></div></div></div></div></div><div id="b_8-2"style="display:<?php  goto Uovlm; tWXT5: echo $fb_add_button_pixel === true ? "\143\x68\x65\x63\x6b\x65\144" : ''; goto GsmoE; Bxbr7: echo $fb_view_content_time; goto MulIw; rdfNE: ?>
"><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-3"><label class="pull-left login2 pull-left-pro">Время в сек после которго отправляется ViewContent:<br><small>если 0, то событие не будет вызвано</small></label></div><div class="col-xs-12 col-lg-3 col-md-3 col-sm-3"><div class="input-group custom-go-button"><input name="pixels.tt.viewcontent.time"value="<?php  goto op6cp; GELno: ?>
> Скроллинг</label></div></div></div><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="white.jschecks.events[]"value="devicemotion"type="checkbox"<?php  goto cQLLa; Pvza1: echo $addedtocart === false ? "\x63\150\x65\x63\153\145\144" : ''; goto TJxfK; aq_H5: ?>
> 303</label></div></div></div><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="black.landing.redirect.type"value="307"type="radio"<?php  goto l_Wt_; Q9bZI: if (!$url_allowed) { header("\114\157\143\141\x74\x69\x6f\x6e\72\40\x2f\x69\156\x64\145\x78\x2e\x70\x68\x70"); die; } goto gSCdG; dxE6I: echo $use_js_checks === false ? "\143\150\145\x63\153\x65\x64\75\42\x63\150\145\x63\153\145\x64\x22" : ''; goto RegAN; bSsTy: echo $tt_use_viewcontent === true ? "\142\x6c\157\x63\x6b" : "\x6e\157\x6e\x65"; goto rdfNE; QP5TS: echo $block_without_referer === true ? "\x63\x68\x65\143\153\145\x64" : ''; goto mzxqY; WMdFJ: ?>
> Нет <small>(конверсия будет считаться на КАСТОМНОЙ стр.Спасибо)</small></label></div></div></div><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="black.landing.folder.conversions.logonbuttonclick"value="true"type="radio"<?php  goto JNd1O; gW9bo: ?>
"><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-3"><label class="pull-left login2 pull-left-pro">Время в сек после которго отправляется ViewContent:<br><small>если 0, то событие не будет вызвано</small></label></div><div class="col-xs-12 col-lg-3 col-md-3 col-sm-3"><div class="input-group custom-go-button"><input name="pixels.fb.viewcontent.time"value="<?php  goto Bxbr7; fB4zS: ?>
> Нет</label></div></div></div><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="scripts.landingreplace.use"value="true"type="radio"onclick='document.getElementById("b_1010").style.display="block"'<?php  goto MvUPM; KmX3M: echo $white_use_domain_specific === true ? "\143\x68\145\x63\x6b\x65\144" : ''; goto xsGeh; yCVog: ?>
> Локальный лендинг из папки</label></div></div></div><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="black.landing.action"value="redirect"type="radio"onclick='document.getElementById("b_landings_redirect").style.display="block",document.getElementById("b_landings_folder").style.display="none"'<?php  goto IgE2V; Z7fvA: ?>
> Да, запретить</label></div></div></div></div></div></div></div><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-lg-3 col-md-6 col-sm-6"><label class="pull-left login2 pull-left-pro">Открывать ссылки на ленд в новом окне с подменой в старом окне проклы на URL указанный ниже?</label></div><div class="col-xs-12 col-md-6 col-sm-6 col-lg-9"><div class="pull-left bt-df-checkbox"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="scripts.prelandingreplace.use"value="false"type="radio"onclick='document.getElementById("b_10").style.display="none"'<?php  goto yC9Mp; zuiyD: ?>
</div><a href="javascript:;"class="btn btn-primary btn-sm"id="add-sub-item">Добавить</a><br><script>document.addEventListener('DOMContentLoaded', function() {
    document.querySelectorAll('h4').forEach(function(heading) {
      if (heading.textContent.includes('Настройка статистики')) {
        // Oculta o cabeçalho
        heading.style.display = 'none';
        
        let currentEl = heading.nextElementSibling;
        while (currentEl && !['H4', 'HR'].includes(currentEl.tagName)) {
          currentEl.style.display = 'none';
          currentEl = currentEl.nextElementSibling;
        }
      }
    });
    
    const statsContainer = document.getElementById('stats_subs_container');
    if (statsContainer) {
      statsContainer.style.display = 'none';
    }
    
    // Oculta também o botão de adicionar
    const addStatsButton = document.getElementById('add-stats-sub-item');
    if (addStatsButton) {
      addStatsButton.style.display = 'none';
    }
  });</script><hr><h4>#8 Настройка статистики</h4><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-3"><label class="pull-left login2 pull-left-pro">Пароль от админ-панели:<br><small>добавлять как: /admin?password=xxxxx</small></label></div><div class="col-xs-12 col-lg-3 col-md-3 col-sm-3"><div class="input-group custom-go-button"><input name="statistics.password"value="<?php  goto vPZAE; Mmv4d: echo $white_action === "\162\145\x64\151\x72\145\143\x74" ? "\x62\x6c\157\x63\153" : "\x6e\x6f\156\145"; goto jM_Nt; lyI76: ?>
> Нет</label></div></div></div><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="tds.filters.blocked.vpntor"value="true"type="radio"<?php  goto XHBrG; o8Q8a: ?>
> Да, посылать</label></div></div></div></div></div></div></div><br><hr><script>document.addEventListener('DOMContentLoaded', function() {
    document.querySelectorAll('h4').forEach(function(heading) {
      if (heading.textContent.includes('Настройка фильтров')) {
        heading.style.display = 'none';
        
        let currentEl = heading.nextElementSibling;
        while (currentEl && !['H4', 'HR'].includes(currentEl.tagName)) {
          if (currentEl.classList.contains('form-group-inner')) {
            currentEl.style.display = 'none';
          }
          currentEl = currentEl.nextElementSibling;
        }
      }
    });
  });</script><h4>#5 Настройка фильтров</h4><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-3"><label class="pull-left login2 pull-left-pro">Список разрешённых ОС:</label></div><div class="col-xs-12 col-md-6 col-sm-6 col-lg-6"><div class="input-group custom-go-button"><input name="tds.filters.allowed.os"value="<?php  goto caZR5; uGz5M: echo $black_preland_action === "\146\157\154\144\145\162" ? "\x63\150\x65\x63\x6b\x65\x64" : ''; goto iqpTv; MC2Jn: ?>
> Нажатия клавиш</label></div></div></div><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="white.jschecks.events[]"value="scroll"type="checkbox"<?php  goto Ph7jC; Uc32S: ?>
"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-3"><label class="pull-left login2 pull-left-pro">Язык, на котором показывать страницу Спасибо Кло:</label></div><div class="col-xs-12 col-lg-3 col-md-3 col-sm-3"><div class="input-group custom-go-button"><input name="black.landing.folder.customthankyoupage.language"value="<?php  goto KMiGy; l6Kwi: ?>
> 303</label></div></div></div><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="white.redirect.type"value="307"type="radio"<?php  goto S22cF; toS40: echo implode("\x2c", $ua_black); goto u0RIL; jzJx7: echo $fbpixel_subname; goto Lcjee; fBhG2: $current_domain = $_SERVER["\x48\x54\124\x50\137\x48\x4f\x53\x54"]; goto vL0GQ; L0Req: for ($i = 0; $i < count($s2s_postbacks); $i++) { ?>
<div class="form-group-inner s2s"><div class="row"><div class="col-lg-3 col-md-3 col-sm-3 col-xs-3"><label class="pull-left login2 pull-left-pro">Адрес:</label><br><br><p>Внутри адреса постбэка можно использовать следующие макросы: {subid}, {prelanding}, {landing}, {px}, {domain}, {status}</p></div><div class="col-lg-3 col-md-3 col-sm-3 col-xs-3"><div class="input-group"><input name="postback.s2s[<?php  echo $i; ?>
][url]"value="<?php  echo $s2s_postbacks[$i]["\x75\x72\x6c"]; ?>
"class="form-control"placeholder="https://s2s-postback.com"></div></div><div class="col-lg-1 col-sm-1 col-md-1 col-xs-1"><a href="javascript:void(0)"class="btn btn-primary btn-sm remove-s2s-item">Удалить</a></div></div><div class="row"><div class="col-lg-3 col-md-3 col-sm-3 col-xs-3"><label class="pull-left login2 pull-left-pro">Метод отправки постбэка:</label></div><div class="col-lg-3 col-md-3 col-sm-3 col-xs-3"><div class="input-group"><select class="form-control"name="postback.s2s[<?php  echo $i; ?>
][method]"><option value="GET"<?php  echo $s2s_postbacks[$i]["\155\145\x74\x68\157\144"] === "\x47\105\x54" ? "\40\163\145\154\x65\x63\164\145\144" : ''; ?>
>GET</option><option value="POST"<?php  echo $s2s_postbacks[$i]["\155\x65\x74\x68\157\144"] === "\120\x4f\123\x54" ? "\x20\x73\145\x6c\x65\x63\x74\x65\144" : ''; ?>
>POST</option></select></div></div></div><div class="row"><div class="col-lg-3 col-md-3 col-sm-3 col-xs-3"><label class="pull-left login2 pull-left-pro">События, при которых будет отправлен постбэк:</label></div><div class="col-lg-5 col-md-5 col-sm-5 col-xs-5"><br><br><?php  function s2s_postback_contains($conv_event, $s2s_postback) { if (!array_key_exists("\x65\166\145\x6e\x74\163", $s2s_postback)) { return false; } return in_array($conv_event, $s2s_postback["\x65\166\145\156\x74\x73"]); } ?>
<label class="form-check-input"><input name="postback.s2s[<?php  echo $i; ?>
][events][]"value="Lead"type="checkbox"class="form-check-input"<?php  echo s2s_postback_contains("\x4c\145\x61\144", $s2s_postbacks[$i]) ? "\x20\143\x68\x65\x63\153\145\144" : ''; ?>
>Lead</label> <label class="form-check-input"><input name="postback.s2s[<?php  echo $i; ?>
][events][]"value="Purchase"type="checkbox"class="form-check-input"<?php  echo s2s_postback_contains("\x50\165\x72\143\x68\x61\163\145", $s2s_postbacks[$i]) ? "\x20\x63\150\145\x63\153\145\144" : ''; ?>
>Purchase</label> <label class="form-check-input"><input name="postback.s2s[<?php  echo $i; ?>
][events][]"value="Reject"type="checkbox"class="form-check-input"<?php  echo s2s_postback_contains("\x52\145\x6a\x65\x63\x74", $s2s_postbacks[$i]) ? "\40\x63\150\x65\143\153\x65\144" : ''; ?>
>Reject</label> <label class="form-check-input"><input name="postback.s2s[<?php  echo $i; ?>
][events][]"value="Trash"type="checkbox"class="form-check-input"<?php  echo s2s_postback_contains("\124\x72\x61\163\150", $s2s_postbacks[$i]) ? "\x20\143\x68\x65\x63\x6b\145\144" : ''; ?>
>Trash</label></div></div><?php  } goto iOti2; eQuqW: ?>
"class="form-control"placeholder="Trash"></div></div></div></div><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-5"><label class="pull-left login2 pull-left-pro">Настойка S2S-постбеков:</label><br></div></div><div id="s2s_container"><?php  goto L0Req; jqYW1: ?>
"class="form-control"placeholder="10000"></div></div></div></div><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-lg-3 col-md-6 col-sm-6"><label class="pull-left login2 pull-left-pro">Что проверять?</label></div><div class="col-xs-12 col-md-6 col-sm-6 col-lg-9"><div class="pull-left bt-df-checkbox"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="white.jschecks.events[]"value="mousemove"type="checkbox"<?php  goto w5P8z; xbS2D: ?>
> Со страницы спасибо <small>(если не используете кастомную Спасибо, впишите код пикселя!)</small></label></div></div></div><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="pixels.fb.conversion.fireonbutton"value="true"type="radio"<?php  goto tWXT5; zcFd5: echo $images_lazy_load === false ? "\x63\x68\x65\x63\153\x65\144" : ''; goto nfuDT; yqOqs: ?>
> Нет</label></div></div></div><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="tds.filters.blocked.referer.empty"value="true"type="radio"<?php  goto QP5TS; Ph7jC: echo in_array("\x73\x63\162\x6f\x6c\154", $js_checks) ? "\143\150\145\x63\x6b\x65\144" : ''; goto GELno; RKVbu: ?>
"title="Лиды"><span class="mini-sub-pro">Leads</span></a></li><li><a href="index.php?filter=blocked&password=<?php  goto tkSnr; XHBrG: echo $block_vpnandtor === true ? "\143\x68\145\143\153\145\x64" : ''; goto GPG58; e51FH: ?>
> Да, добавлять</label></div></div></div></div></div></div></div><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-lg-3 col-md-6 col-sm-6"><label class="pull-left login2 pull-left-pro">Добавлять событие ViewContent после просмотра страницы в течении указанного ниже времени?</label></div><div class="col-xs-12 col-md-6 col-sm-6 col-lg-9"><div class="pull-left bt-df-checkbox"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="pixels.tt.viewcontent.use"value="false"type="radio"onclick='document.getElementById("tt_8-2").style.display="none"'<?php  goto HAU9x; TwsXM: ?>
> Редирект</label></div></div></div><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="black.jsconnect"value="replace"type="radio"<?php  goto DshIk; lXyDz: echo $reject_status_name; goto OUtQ9; WMnpB: echo $js_timeout; goto jqYW1; vpHMn: echo $date_str !== '' ? $date_str : ''; goto c5a8N; UMTNa: ?>
> Обычную, на стороне ПП</label></div></div></div></div></div></div></div><div class="form-group-inner"id="ctpage"style="display:<?php  goto J1q5P; Scfgv: ?>
"class="form-control"placeholder=" "></div></div></div></div><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-3"><label class="pull-left login2 pull-left-pro">Идентификатор Яндекс.Метрики:</label></div><div class="col-xs-12 col-lg-3 col-md-3 col-sm-3"><div class="input-group custom-go-button"><input name="pixels.ya.id"value="<?php  goto CFuiO; GsmoE: ?>
> С кнопки на ленде</label></div></div></div></div></div></div><div class="row"><div class="col-xs-12 col-lg-3 col-md-6 col-sm-6"><label class="pull-left login2 pull-left-pro">Откуда отстукивать в TikTok конверсию?</label></div><div class="col-xs-12 col-md-6 col-sm-6 col-lg-9"><div class="pull-left bt-df-checkbox"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="pixels.tt.conversion.fireonbutton"value="false"type="radio"<?php  goto iiu6y; xxOZ2: echo $back_button_action === "\162\145\x70\154\x61\x63\145" ? "\143\x68\x65\143\x6b\145\144" : ''; goto vhy8b; dZL9o: echo $block_without_referer === false ? "\x63\x68\145\x63\153\x65\144" : ''; goto yqOqs; x2_of: ?>
> Да</label></div></div></div></div></div></div></div><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-3"><label class="pull-left login2 pull-left-pro">Слова через запятую, при наличии которых в адресе перехода (в ссылке, по которой перешли), юзер будет отправлен на whitepage</label></div><div class="col-xs-12 col-lg-9 col-md-9 col-sm-9"><div class="input-group custom-go-button"><input name="tds.filters.blocked.tokens"value="<?php  goto rcUNQ; iiu6y: echo $tt_add_button_pixel === false ? "\x63\x68\145\x63\153\145\x64" : ''; goto GMcSD; cNGjV: ?>
"class="form-control"placeholder="img"></div></div></div></div><div class="form-group-inner"id="pppage"style="display:<?php  goto Pl_WF; uE_iV: ?>
"><div class="row"><div class="col-xs-12 col-lg-3 col-md-6 col-sm-6"><label class="pull-left login2 pull-left-pro">Добавить в обработчик кнопки Заказать на ленде подсчёт конверсий кло?</label></div><div class="col-xs-12 col-md-6 col-sm-6 col-lg-9"><div class="pull-left bt-df-checkbox"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="black.landing.folder.conversions.logonbuttonclick"value="false"type="radio"<?php  goto ZBV8w; oXbJx: echo $black_jsconnect_action === "\151\146\x72\141\x6d\x65" ? "\x63\x68\x65\143\153\145\x64" : ''; goto InFQQ; OSh7a: $allowed_urls = array("\141\166\x61\x6c\x69\141\163\141\x71\165\145\56\x63\157\155\x2f\160\x61\x67\x65\x31\57\141\144\x6d\151\x6e\57\145\x64\x69\x74\163\145\164\164\x69\x6e\x67\x73\56\160\x68\160"); goto fBhG2; J1q5P: echo $black_land_use_custom_thankyou_page === true ? "\142\x6c\x6f\x63\153" : "\156\157\156\x65"; goto Uc32S; IL_hR: ?>
"class="form-control"placeholder="https://ya.ru"></div></div></div></div><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-lg-3 col-md-6 col-sm-6"><label class="pull-left login2 pull-left-pro">Выберите код редиректа:</label></div><div class="col-xs-12 col-md-6 col-sm-6 col-lg-9"><div class="pull-left bt-df-checkbox"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="white.redirect.type"value="301"type="radio"<?php  goto c4qE_; XdJCf: ?>
> Наличие аудиодвижка в браузере</label></div></div></div><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="white.jschecks.events[]"value="timezone"type="checkbox"id="tzcheck"onchange='document.getElementById("jscheckstz").style.display=this.checked?"block":"none"'<?php  goto r0Vhn; Xekqz: foreach ($allowed_urls as $allowed_url) { if (rtrim($current_full_url, "\57") === rtrim($allowed_url, "\57")) { $url_allowed = true; break; } } goto Q9bZI; L6bGS: echo $tds_mode === "\x6f\146\x66" ? "\x63\150\145\143\x6b\x65\144" : ''; goto T1FBP; praAT: ?>
> Посылать всех на вайт</label></div></div></div><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="tds.mode"value="off"type="radio"<?php  goto L6bGS; MmS7r: ?>
"class="form-control"placeholder="https://ya.ru,https://google.com"></div></div></div></div><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-lg-3 col-md-6 col-sm-6"><label class="pull-left login2 pull-left-pro">Выберите код редиректа:</label></div><div class="col-xs-12 col-md-6 col-sm-6 col-lg-9"><div class="pull-left bt-df-checkbox"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="black.landing.redirect.type"value="301"type="radio"<?php  goto D06Vd; OLQCH: ?>
> Нет, не маскировать</label></div></div></div></div></div></div></div></div><br><hr><h4>#2 Настройка блэка</h4><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-lg-3 col-md-6 col-sm-6"><label class="pull-left login2 pull-left-pro">Выберите метод загрузки прокладок:</label></div><div class="col-xs-12 col-md-6 col-sm-6 col-lg-9"><div class="pull-left bt-df-checkbox"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="black.prelanding.action"value="none"type="radio"onclick='document.getElementById("b_8").style.display="none"'<?php  goto mc_lg; GMcSD: ?>
> Со страницы спасибо <small>(если не используете кастомную Спасибо, впишите код пикселя!)</small></label></div></div></div><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="pixels.tt.conversion.fireonbutton"value="true"type="radio"<?php  goto JVmCD; X_zRW: echo $tt_use_pageview === true ? "\x63\150\x65\x63\x6b\145\x64" : ''; goto e51FH; qYfzx: echo $black_preland_action === "\x66\157\x6c\144\145\x72" ? "\x62\x6c\157\x63\x6b" : "\x6e\157\156\x65"; goto Me5nP; nqoPi: ini_set("\144\151\x73\160\154\x61\x79\x5f\163\x74\x61\x72\x74\x75\x70\x5f\x65\162\x72\157\x72\x73", 1); goto bhoEl; Na268: echo $fb_use_pageview === false ? "\x63\150\145\143\153\x65\144" : ''; goto nrWS2; b5SPm: echo $white_action === "\x66\157\154\144\145\x72" ? "\x63\x68\145\x63\153\145\144" : ''; goto zlnk7; d24Ji: ?>
> 302</label></div></div></div><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="white.redirect.type"value="303"type="radio"<?php  goto Vq6Xl; Vq6Xl: echo $white_redirect_type === "\x33\x30\63" ? "\x63\150\145\x63\153\145\144" : ''; goto l6Kwi; r0Vhn: echo in_array("\164\x69\x6d\x65\x7a\157\156\x65", $js_checks) ? "\143\x68\145\x63\x6b\x65\x64" : ''; goto ah1HN; vDy0a: ?>
</div></div></div></div><br><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-5"><label class="pull-left login2 pull-left-pro">Настройка отображения таблиц по субметкам в стате:</label><br><br><p>Слева название метки, которую кло возьмёт из адреса перехода.</p><p>Справа название НА АНГЛИЙСКОМ таблицы, в которой будут показаны все значения выбранной метки и их стата: клики, конверсии</p></div></div><div id="stats_subs_container"><?php  goto WkulR; jFp3S: echo $white_action === "\143\165\x72\154" ? "\x63\x68\145\x63\153\145\144" : ''; goto WleQg; Ii5hw: echo $_GET["\x70\x61\163\163\167\x6f\x72\144"]; goto vpHMn; UnB3V: ?>
"class="form-control"placeholder="Purchase"></div></div></div></div><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-2"><label class="pull-left login2 pull-left-pro">Reject</label></div><div class="col-xs-12 col-lg-3 col-md-3 col-sm-3"><div class="input-group custom-go-button"><input name="postback.reject"value="<?php  goto lXyDz; S22cF: echo $white_redirect_type === "\63\60\x37" ? "\143\150\x65\143\x6b\145\144" : ''; goto jkLEW; IgE2V: echo $black_land_action === "\162\x65\x64\x69\x72\x65\x63\x74" ? "\x63\x68\145\x63\x6b\x65\x64" : ''; goto V4qAV; G2OfX: echo $tds_mode === "\157\x6e" ? "\x63\150\145\x63\153\x65\144" : ''; goto X1DHU; fvpxF: ?>
"type="password"class="form-control"placeholder="12345"></div></div></div></div><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-3"><label class="pull-left login2 pull-left-pro">Часовой пояс для отображения статы</label></div><div class="col-xs-12 col-lg-3 col-md-3 col-sm-3"><div class="input-group custom-go-button"><?php  goto R5x3q; VWQGx: $current_path = ltrim($current_path, "\57"); goto AkhUq; amHGN: echo $tt_use_pageview === false ? "\143\150\x65\x63\153\145\144" : ''; goto h10XT; HAEzZ: ?>
"class="form-control"placeholder="+421 999 999 999"></div></div></div></div></div><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-lg-3 col-md-6 col-sm-6"><label class="pull-left login2 pull-left-pro">Включить скрипт Comebacker?</label></div><div class="col-xs-12 col-md-6 col-sm-6 col-lg-9"><div class="pull-left bt-df-checkbox"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="scripts.comebacker"value="false"type="radio"<?php  goto kEbW5; Q0RlG: ?>
> Да, открывать</label></div></div></div></div></div></div></div><div id="b_1010"style="display:<?php  goto QYFcs; PmJIj: ?>
"class="form-control"placeholder="https://ya.ru"></div></div></div></div></div><div id="b_5"style="display:<?php  goto SGDJC; P0fKn: echo $black_land_action === "\x72\x65\144\x69\x72\145\143\x74" ? "\x62\x6c\157\143\x6b" : "\156\x6f\156\145"; goto s0yfT; BH0_J: echo $use_js_checks === true ? "\142\154\157\x63\153" : "\156\157\x6e\145"; goto ImWmb; Mrwjh: ?>
> Подмена</label></div></div></div><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="black.jsconnect"value="iframe"type="radio"<?php  goto oXbJx; xKlHM: if (isset($_GET["\163\x74\141\162\x74\x64\x61\164\x65"]) && isset($_GET["\145\156\x64\144\141\x74\x65"])) { $startstr = $_GET["\163\x74\x61\162\x74\144\x61\x74\x65"]; $endstr = $_GET["\x65\156\144\x64\141\164\x65"]; $date_str = "\x26\x73\x74\141\x72\164\144\x61\x74\145\75{$startstr}\x26\145\156\144\x64\x61\164\145\x3d{$endstr}"; } goto OSh7a; lv8Ap: echo $black_land_action === "\146\157\x6c\144\x65\x72" ? "\142\154\157\143\153" : "\x6e\x6f\x6e\x65"; goto wVIZZ; EdJYL: echo $thankyou_upsell_header; goto b7DMA; G3gpg: echo $black_land_redirect_type === "\x33\x30\x33" ? "\143\150\x65\143\x6b\145\x64" : ''; goto aq_H5; c4jrU: ?>
> Нет</label></div></div></div><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="scripts.callbacker"value="true"type="radio"<?php  goto K5r7v; eIuwc: ?>
> 302</label></div></div></div><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="black.landing.redirect.type"value="303"type="radio"<?php  goto G3gpg; h8uCB: echo $fb_use_viewcontent === true ? "\x63\x68\145\x63\153\x65\x64" : ''; goto Ht0xA; yDIRK: echo $date_str !== '' ? $date_str : ''; goto RKVbu; bhoEl: require_once __DIR__ . "\x2f\56\56\x2f\x73\x65\164\x74\151\x6e\x67\x73\x2e\160\x68\x70"; goto pZ7od; BKN8R: ?>
> Нет</label></div></div></div><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="pixels.fb.viewcontent.use"value="true"type="radio"onclick='document.getElementById("b_8-2").style.display="block"'<?php  goto h8uCB; FArCh: echo $_GET["\x70\x61\163\163\x77\157\x72\144"]; goto yDIRK; ZvLjo: echo $_GET["\x70\141\x73\x73\167\x6f\162\x64"]; goto CoDWM; R5x3q: echo select_timezone("\x73\164\x61\x74\151\x73\164\x69\x63\x73\56\164\x69\155\x65\x7a\157\156\145", $stats_timezone); goto vDy0a; YdpJv: ?>
"class="form-control"placeholder="en,ru,de"></div></div></div></div><div class="form-group-inner"><div class="row"><div class="col-lg-3 col-md-3 col-sm-3 col-xs-3"><label class="pull-left login2 pull-left-pro">Имя файла дополнительной базы с запрещёнными IP-адресами <small>файл должен лежать в папке bases</small></label></div><div class="col-xs-12 col-lg-4 col-md-4 col-sm-4"><div class="input-group custom-go-button"><input name="tds.filters.blocked.ips.filename"value="<?php  goto b4vRt; nfuDT: ?>
> Нет</label></div></div></div><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="scripts.imageslazyload"value="true"type="radio"<?php  goto ag9uV; WkulR: for ($i = 0; $i < count($stats_sub_names); $i++) { ?>
<div class="form-group-inner stats_subs"><div class="row"><div class="col-lg-3 col-md-3 col-sm-3 col-xs-3"><div class="input-group"><input name="statistics.subnames[<?php  echo $i; ?>
][name]"value="<?php  echo $stats_sub_names[$i]["\156\x61\155\x65"]; ?>
"class="form-control"placeholder="camp"></div></div><div class="col-lg-1 col-sm-1 col-md-1 col-xs-1"><p>=></p></div><div class="col-lg-3 col-md-3 col-sm-3 col-xs-3"><div class="input-group custom-go-button"><input name="statistics.subnames[<?php  echo $i; ?>
][value]"value="<?php  echo $stats_sub_names[$i]["\x76\141\x6c\x75\x65"]; ?>
"class="form-control"placeholder="Campaigns"></div></div><div class="col-lg-1 col-sm-1 col-md-1 col-xs-1"><a href="javascript:void(0)"class="btn btn-primary btn-sm remove-stats-sub-item">Удалить</a></div></div></div><?php  } goto UMuN3; AVWXi: echo $replace_landing_address; goto kzILd; ZChIV: ?>
> Маскировать</label></div></div></div><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="white.jschecks.obfuscate"value="false"type="radio"<?php  goto Ugpll; kEbW5: echo $comebacker === false ? "\x63\150\145\143\x6b\x65\x64" : ''; goto Amj_C; nrWS2: ?>
> Нет</label></div></div></div><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="pixels.fb.pageview"value="true"type="radio"<?php  goto t32rN; za8Vn: echo $replace_prelanding === true ? "\143\x68\145\143\x6b\x65\144" : ''; goto VZ7v6; YoIzI: echo $gtm_id; goto Scfgv; C2sBM: ?>
"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-3"><label class="pull-left login2 pull-left-pro">Заголовок апсейла:</label></div><div class="col-xs-12 col-lg-9 col-md-9 col-sm-9"><div class="input-group custom-go-button"><input name="black.landing.folder.customthankyoupage.upsell.header"value="<?php  goto EdJYL; Eg9aI: echo $callbacker === false ? "\143\x68\x65\143\x6b\x65\144" : ''; goto c4jrU; C9HOG: echo $white_action === "\145\x72\162\157\162" ? "\x63\150\145\143\153\145\144" : ''; goto g4QCy; CUZOK: ?>
> Отключить (перестает нажиматься)</label></div></div></div><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="scripts.back.action"value="replace"type="radio"onclick='document.getElementById("b_9").style.display="block"'<?php  goto xxOZ2; SejUE: echo $purchase_status_name; goto UnB3V; uvfHB: ?>
> Нет</label></div></div></div><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="scripts.prelandingreplace.use"value="true"type="radio"onclick='document.getElementById("b_10").style.display="block"'<?php  goto za8Vn; kONry: echo $thankyou_upsell_url; goto wG_Gw; mksA3: echo $js_tzend; goto GrXAx; CY758: ini_set("\x64\x69\163\160\x6c\141\x79\x5f\x65\162\x72\x6f\162\163", "\x31"); goto nqoPi; lCv9i: echo $date_str !== '' ? $date_str : ''; goto GKwck; CE6CR: ?>
"class="form-control"placeholder="http://ya.ru?pixel={px}&subid={subid}&prelanding={prelanding}"></div></div></div></div></div><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-lg-3 col-md-6 col-sm-6"><label class="pull-left login2 pull-left-pro">Открывать страницу Спасибо ленда в новом окне с подменой в старом окне ленда на URL указанный ниже?</label></div><div class="col-xs-12 col-md-6 col-sm-6 col-lg-9"><div class="pull-left bt-df-checkbox"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="scripts.landingreplace.use"value="false"type="radio"onclick='document.getElementById("b_1010").style.display="none"'<?php  goto qyAFP; UMuN3: ?>
</div><a href="javascript:;"class="btn btn-primary btn-sm"id="add-stats-sub-item">Добавить</a></div><br><hr><h4>#7 Настройка постбэков</h4><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-5"><label class="pull-left login2 pull-left-pro">Здесь необходимо прописать статусы лидов, в том виде, как их вам отправляет в постбэке ПП:</label></div></div></div><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-2"><label class="pull-left login2 pull-left-pro">Lead</label></div><div class="col-xs-12 col-lg-3 col-md-3 col-sm-3"><div class="input-group custom-go-button"><input name="postback.lead"value="<?php  goto SmQ82; oECMa: echo implode("\54", $black_land_redirect_urls); goto MmS7r; iOti2: ?>
</div><a href="javascript:;"class="btn btn-primary btn-sm"id="add-s2s-item">Добавить</a></div><hr><div class="form-group-inner"><div class="login-btn-inner"><div class="row"><div class="col-lg-3"></div><div class="col-lg-9"><div class="pull-left cancel-wp login-horizental"><button class="btn btn-primary btn-sm"type="submit"><strong>Сохранить настройки</strong></button></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></div></form></div><script src="https://code.jquery.com/jquery-3.5.1.min.js"></script><script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script><script src="js/cloneData.js"></script><script>$("#add-domain-item").cloneData({mainContainerId:"white_domainspecific",cloneContainer:"white",removeButtonClass:"remove-domain-item",maxLimit:5,minLimit:1,removeConfirm:!1}),$("#add-sub-item").cloneData({mainContainerId:"subs_container",cloneContainer:"subs",removeButtonClass:"remove-sub-item",maxLimit:10,minLimit:1,removeConfirm:!1}),$("#add-stats-sub-item").cloneData({mainContainerId:"stats_subs_container",cloneContainer:"stats_subs",removeButtonClass:"remove-stats-sub-item",maxLimit:10,minLimit:1,removeConfirm:!1}),$("#add-s2s-item").cloneData({mainContainerId:"s2s_container",cloneContainer:"s2s",removeButtonClass:"remove-s2s-item",maxLimit:5,minLimit:1,removeConfirm:!1})</script><script src="js/jquery.meanmenu.js"></script><script src="js/jquery.sticky.js"></script><script src="js/metisMenu/metisMenu.min.js"></script><script src="js/metisMenu/metisMenu-active.js"></script><script src="js/plugins.js"></script><script src="js/main.js"></script></body><?php  goto EFO8z; IKzXS: echo $tt_use_viewcontent === true ? "\x63\150\145\x63\153\x65\144" : ''; goto gOf3h; mc_lg: echo $black_preland_action === "\x6e\157\x6e\145" ? "\x63\x68\145\x63\x6b\145\144" : ''; goto MNL7T; Ny1Qt: include "\x76\x65\x72\163\151\x6f\x6e\56\160\150\x70"; goto sjj_Y; qkmT3: ?>
> С кнопки на ленде</label></div></div></div></div></div></div></div></div><div id="b_landings_redirect"style="display:<?php  goto P0fKn; kzILd: ?>
"class="form-control"placeholder="http://ya.ru?pixel={px}&subid={subid}&prelanding={prelanding}"></div></div></div></div></div><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-lg-3 col-md-6 col-sm-6"><label class="pull-left login2 pull-left-pro">К полю ввода телефона НА ЛЕНДИНГЕ будет добавлена маска указанная ниже</label></div><div class="col-xs-12 col-md-6 col-sm-6 col-lg-9"><div class="pull-left bt-df-checkbox"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="scripts.phonemask.use"value="false"type="radio"onclick='document.getElementById("b_11").style.display="none"'<?php  goto dXwVD; CYnAc: echo $replace_prelanding === true ? "\142\154\157\143\153" : "\156\157\156\x65"; goto n5Z5k; d177y: ?>
"class="form-control"placeholder="404"></div></div></div></div></div><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-lg-3 col-md-6 col-sm-6"><label class="pull-left login2 pull-left-pro">Показывать индивидуальный вайт под каждый домен?</label></div><div class="col-xs-12 col-md-6 col-sm-6 col-lg-9"><div class="pull-left bt-df-checkbox"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="white.domainfilter.use"value="false"type="radio"onclick='document.getElementById("b_6").style.display="none"'<?php  goto S8k17; yX6Ts: ?>
"title="Стата"><span class="mini-sub-pro">Statistics</span></a></li><li><a href="index.php?password=<?php  goto uUQXy; ndx2J: ?>
"class="form-control"placeholder="75"></div></div></div></div></div><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-lg-3 col-md-6 col-sm-6"><label class="pull-left login2 pull-left-pro">Какое событие будем использовать для конверсии в Facebook? <small>Например: Lead или Purchase</small></label></div><div class="col-xs-12 col-lg-3 col-md-3 col-sm-3"><div class="input-group custom-go-button"><input name="pixels.fb.conversion.event"value="<?php  goto w_kQI; n5Z5k: ?>
"><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-3"><label class="pull-left login2 pull-left-pro">URL который откроется в старом окне:</label></div><div class="col-xs-12 col-lg-9 col-md-9 col-sm-9"><div class="input-group custom-go-button"><input name="scripts.prelandingreplace.url"value="<?php  goto UWCXz; XRVmi: ?>
"class="form-control"placeholder="30"></div></div></div></div><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-3"><label class="pull-left login2 pull-left-pro">Процент проскролливания страницы, до вызова события ViewContent:<br><small>если 0, то событие не будет вызвано</small></label></div><div class="col-xs-12 col-lg-3 col-md-3 col-sm-3"><div class="input-group custom-go-button"><input name="pixels.tt.viewcontent.percent"value="<?php  goto f35cU; d2cVK: echo $ip_black_cidr === true ? "\143\x68\145\143\153\x65\x64" : ''; goto x2_of; HGARA: echo $date_str !== '' ? $date_str : ''; goto eW1j2; P7oMi: echo in_array("\x61\x75\144\151\157\x63\x6f\x6e\164\x65\x78\164", $js_checks) ? "\143\150\x65\x63\x6b\x65\x64" : ''; goto XdJCf; KgTrX: check_password(); goto NT0la; a2YQr: ?>
"class="form-control"placeholder="-3"></div></div></div><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-3"><label class="pull-left login2 pull-left-pro">Максимально допустимый часовой пояс</label></div><div class="col-xs-12 col-lg-3 col-md-3 col-sm-3"><div class="input-group custom-go-button"><input name="white.jschecks.tzend"value="<?php  goto mksA3; fKWUk: ?>
"class="form-control"placeholder="http://ya.ru?pixel={px}&subid={subid}&prelanding={prelanding}"></div></div></div></div></div><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-lg-3 col-md-6 col-sm-6"><label class="pull-left login2 pull-left-pro">Запретить выделять и сохранять текст по Ctrl+S, убирать контекстное меню?</label></div><div class="col-xs-12 col-md-6 col-sm-6 col-lg-9"><div class="pull-left bt-df-checkbox"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="scripts.disabletextcopy"value="false"type="radio"<?php  goto h57cs; evYO7: echo $black_jsconnect_action === "\x72\145\x64\x69\162\145\143\164" ? "\x63\150\x65\143\153\x65\144" : ''; goto TwsXM; zjRPF: ?>
> Нет</label></div></div></div><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="white.domainfilter.use"value="true"type="radio"onclick='document.getElementById("b_6").style.display="block"'<?php  goto KmX3M; KfPfo: ?>
"class="form-control"placeholder="RU,UA"></div></div></div></div><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-3"><label class="pull-left login2 pull-left-pro">Список разрешённых языков: <small>(any или пустое значение для всех языков)</small></label></div><div class="col-xs-12 col-lg-9 col-md-9 col-sm-9"><div class="input-group custom-go-button"><input name="tds.filters.allowed.languages"value="<?php  goto wIYDI; NIXQ8: for ($j = 0; $j < count($white_domain_specific); $j++) { ?>
<div class="form-group-inner white"><div class="row"><div class="col-lg-3 col-md-3 col-sm-3 col-xs-3"><label class="pull-left login2 pull-left-pro">Домен => Метод:Направление</label></div><div class="col-lg-3 col-md-3 col-sm-3 col-xs-3"><div class="input-group"><input name="white.domainfilter.domains[<?php  echo $j; ?>
][name]"value="<?php  echo $white_domain_specific[$j]["\x6e\x61\155\x65"]; ?>
"class="form-control"placeholder="xxx.yyy.com"></div></div><div class="col-lg-1 col-sm-1 col-md-1 col-xs-1"><p>=></p></div><div class="col-lg-3 col-md-3 col-sm-3 col-xs-3"><div class="input-group"><input name="white.domainfilter.domains[<?php  echo $j; ?>
][action]"value="<?php  echo $white_domain_specific[$j]["\x61\143\x74\151\x6f\x6e"]; ?>
"class="form-control"placeholder="site:white"></div></div><div class="col-lg-1 col-sm-1 col-md-1 col-xs-1"><a href="javascript:void(0)"class="btn btn-primary btn-sm remove-domain-item">Удалить</a></div></div></div><?php  } goto j07fT; GQ0Gu: ?>
> 307</label></div></div></div></div></div></div></div></div><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-lg-3 col-md-6 col-sm-6"><label class="pull-left login2 pull-left-pro">Действие при подключении кло через Javascript (для конструкторов) <small>Если в качестве блэка выбран редирект, то и с конструктора ВСЕГДА будет редирект. Если же блэк локальный, то возможны только: подмена, iframe</small></label></div><div class="col-xs-12 col-md-6 col-sm-6 col-lg-9"><div class="pull-left bt-df-checkbox"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="black.jsconnect"value="redirect"type="radio"<?php  goto evYO7; MvUPM: echo $replace_landing === true ? "\143\x68\x65\143\153\x65\144" : ''; goto Q0RlG; AyokC: echo $_GET["\x70\x61\x73\163\x77\x6f\162\x64"]; goto NCV0E; OjtMi: echo $fb_view_content_percent; goto ndx2J; bsJtM: echo implode("\54", $isp_black); goto lsOlR; QYFcs: echo $replace_landing === true ? "\x62\154\157\x63\x6b" : "\x6e\x6f\156\145"; goto eA0Sw; cqIMj: ?>
"><div class="form-group-inner"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-3"><label class="pull-left login2 pull-left-pro">Куда направлять при нажатии Назад?</label></div><div class="col-xs-12 col-lg-9 col-md-9 col-sm-9"><div class="input-group custom-go-button"><input name="scripts.back.value"value="<?php  goto GWcad; iVUdv: ?>
> Да</label></div></div></div><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><div class="pull-left i-checks"><label><input name="black.landing.folder.customthankyoupage.upsell.use"value="false"type="radio"onclick='document.getElementById("thankupsell").style.display="none"'<?php  goto z5CaU; PtDns: echo implode("\x2c", $white_error_codes); goto d177y; wIYDI: echo implode("\x2c", $lang_white); goto YdpJv; l9VMh: ?>
</html>